name: CI
on: [push, pull_request]
jobs:
  test:
    name: Node ${{ matrix.node }}, Mongo ${{ matrix.mongodb-version }}, Agenda ${{ matrix.agenda-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['12', '14', '16']
        mongodb-version: [ 3.6, 4.0, 4.2, 4.4 ]
        agenda-version: [ 3.1, 4.0 ]
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js v${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - run: npm install

      - name: Install agenda
        run: npm i agenda@${{ matrix.agenda-version }}

      - run: npm test
        env:
          CI: true
